### ISSUE TITLE
Epsilon

### ISSUE THREAD

**Issue by XEverentX** [KchnKchn/numerical-methods-labs#1]
https://github.com/KchnKchn/numerical-methods-labs/blob/018d31e04cd0d949fb76213db37b7405fe2bc033/task11/main_window/main_window.py#L403

В следующих сравнениях  ты сравниваешь  s_curr с epsilon/15, а тут просто с epsilon 
При этом сам s_curr делится на 15

Это окей?
И что вообще значит деление именно на 15?

**Comment by KchnKchn** [comment]
Оценка локальной погрешности в точке (V2 - V) / (2^p - 1), где V2 - точка полученная двойным счетом, V - точка полученная одинарным счетом, p - порядок метода. В нашем методе порядок равен четырем, поэтому делим на пятнадцать.

**Comment by XEverentX** [comment]
Ну а почему ты везде, кромек этого ифа делить eps на 15, а тут нет?

**Comment by XEverentX** [comment]
А, хотя вроде понял
